### ISSUE TITLE
Ability to deploy on server

### ISSUE THREAD

**Issue by awhipp** [iobio/vcf.iobio.io#63]
Currently looking to deploy this in a secure environment with various S3 buckets containing VCF files. 

It does not appear that it is possible give that it opens a websocket to `nv-prod.iobio.io/` and that server does not have aws access to our buckets so the retrieval fails.

Is there any way to set this up? There's not much in terms of documentation.

**Comment by chmille4** [comment]
The easiest way to get things working is to create an expiring signed s3 url for your vcf files and then simply run them on the vcf.iobio.io site. This provides some level of security but the data is still being sent out to the public iobio servers.

If that is not sufficiently secure we do have some commercial options that can be setup in a secure Virtual Private Cloud or on-premise.

**Comment by awhipp** [comment]
Ah okay, we did not realize that the source was only open for the front-end. The value add for our client doesn't warrant any additional funding. We will just skip this requirement.

Appreciate the information.
